[package]
name = "mdbook"
version = "0.0.0"
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
timely = { path = "../timely" }
timely_bytes = { path = "../bytes" }
timely_communication = { path = "../communication" }
serde = "1.0"
